const data = {
  food: [
    { id: 0, name: "برنج ", calaryG: 360, count: "100 گرم" },
    {
      id: 1,
      name: "( زرده خالی ) تخم مرغ ",
      calary: 50,
      count: "1عدد ",
    },
    {
      id: 2,
      name: "تخم مرغ ( سفیده خالی ) ",
      calary: 20,
      count: "1عدد ",
    },
    { id: 3, name: "تخم مرغ نیمرو ", calaryG: 130, count: "1عدد " },
    { id: 4, name: "تخم مرغ آب پز ", calaryG: 70, count: "1عدد " },
    { id: 5, name: "عدس   ", calaryG: 360, count: "100 گرم" },
    { id: 6, name: "کله پاچه ", calaryG: 190, count: "100 گرم" },
    { id: 7, name: "کوفته  ", calaryG: 150, count: "1عدد " },
    { id: 8, name: "کتلت  ", calaryG: 150, count: "1عدد " },
    { id: 9, name: "برگ", calaryG: 200, count: "100 گرم" },
    { id: 10, name: "بامیه سبز ", calaryG: 40, count: "100 گرم" },
    { id: 11, name: "جگر یک سیخ ", calaryG: 80, count: "100 گرم" },
    { id: 12, name: "جگر سفید ", calaryG: 160, count: "100 گرم" },
    { id: 13, name: "جگر سرخ کرده ", calaryG: 350, count: "100 گرم" },
    {
      id: 14,
      name: "سوپ مرغ با سبزیجات",
      calaryG: 30,
      count: "100 گرم",
    },
    { id: 15, name: "سو سیس ", calaryG: 300, count: "100 گرم" },
    { id: 16, name: "سس مایونز ", calaryG: 720, count: "100 گرم" },
    { id: 17, name: "سیرابی ", calaryG: 130, count: "100 گرم" },
    { id: 18, name: "لوبیا سبز ", calaryG: 30, count: "100 گرم" },
    { id: 19, name: "لوبیا قرمز ", calaryG: 340, count: "100 گرم" },
    { id: 20, name: "لوبیا چشم بلبلی پخته ", calaryG: 80, count: "100 گرم" },
    { id: 21, name: "لپه پخته ", calaryG: 115, count: "100 گرم" },
    { id: 22, name: "ماکارونی ", calaryG: 360, count: "100 گرم" },
    { id: 23, name: "ماهی ", calaryG: 100, count: "100 گرم" },
    { id: 24, name: "گوشت مرغ ", calaryG: 200, count: "100 گرم" },
    { id: 25, name: "گوشت گاو ", calaryG: 240, count: "100 گرم" },
    { id: 26, name: "کباب کوبیده ", calaryG: 270, count: "1 سیخ" },
    { id: 27, name: "کباب برگ ", calaryG: 200, count: "1 سیخ" },
    { id: 28, name: "کشک ", calaryG: 380, count: "100 گرم" },
    { id: 29, name: "سویا ", calaryG: 30, count: "100 گرم" },
    { id: 30, name: "جوانه گندم ", calaryG: 50, count: "100 گرم" },
    { id: 31, name: "کدو خورشتی ", calaryG: 28, count: "100 گرم" },
    { id: 32, name: " کرفس ", calaryG: 13, count: "100 گرم" },
    { id: 33, name: " آش دوغ", calaryG: 250, count: "1 لیوان" },
    { id: 33, name: "آش رشته ", calaryG: 250, count: "1 لیوان" },
    { id: 33, name: "آش جو ", calaryG: 250, count: "1 لیوان" },
  ],
  fastFood: [
    { id: 0, name: "پیتزا ", calaryG: 700, count: "1 عدد" },
    {
      id: 1,
      name: "پنیر پیتزا ",
      calary: 450,
      count: "100 گزم ",
    },
    {
      id: 2,
      name: "پوره سیب زمینی ",
      calary: 180,
      count: "1 لیوان",
    },
    { id: 3, name: "", calaryG: 520, count: "گرم 100 " },
    { id: 4, name: "سمبوسه ", calaryG: 380, count: "1 عدد " },
    { id: 5, name: "سو سیس", calaryG: 300, count: "100 گرم" },
    { id: 6, name: "ساندویچ همبرگر ", calaryG: 350, count: "1 عدد" },
    { id: 7, name: "کالباس  ", calaryG: 300, count: "1عدد " },
    { id: 8, name: "نوشابه  ", calaryG: 120, count: "1 شیشه " },
    { id: 9, name: "استیک کم چرب  ", calaryG: 100, count: "100 گرم " },
    { id: 10, name: "قارچ", calaryG: 27, count: "100 گرم " },
    { id: 11, name: "گو جه فرنگی ( سس )", calaryG: 110, count: "100 گرم " },
  ],
  furits: [
    { id: 0, name: "آلبالو  ", calaryG: 60, count: "1 لیوان" },

    {
      id: 1,
      name: "آلوی زرد",
      calary: 70,
      count: "100 گزم ",
    },
    {
      id: 2,
      name: "آلوی قرمز",
      calary: 50,
      count: "100 گرم",
    },
    { id: 3, name: "انار تازه دانه شده", calaryG: 60, count: "گرم 100 " },
    { id: 4, name: "انجیر تازه ", calaryG: 60, count: "1 عدد " },
    { id: 5, name: "انجیر خشک", calaryG: 270, count: "100 گرم" },
    { id: 6, name: "انگور ", calaryG: 85, count: "100 گرم" },
    { id: 7, name: "تربچه  ", calaryG: 2, count: "1عدد " },
    { id: 8, name: "تمشک  ", calaryG: 80, count: "100 گرم" },
    { id: 9, name: "خیار", calaryG: 5, count: "100 گرم" },
    { id: 10, name: "خربزه", calaryG: 23, count: "100 گرم" },

    { id: 11, name: "خرمالو ", calaryG: 80, count: "120 گرم" },

    { id: 12, name: "ریواس", calaryG: 15, count: "100 گرم" },
    { id: 13, name: "زردآلو", calaryG: 50, count: "100 گرم" },

    { id: 14, name: "زردآلو (برگه خشک)", calaryG: 270, count: "100 گرم" },
    { id: 15, name: "سیب درختی", calaryG: 55, count: "100 گرم" },

    { id: 16, name: "شاه توت", calaryG: 60, count: "100 گرم" },

    { id: 17, name: "گریپ فروت", calaryG: 30, count: "100 گرم" },

    { id: 18, name: "طالبی", calaryG: 23, count: "100 گرم" },

    { id: 19, name: "گوجه ", calaryG: 15, count: "100 گرم" },
    { id: 20, name: "گیلاس ", calaryG: 60, count: "100 گرم" },
    { id: 21, name: "گوجه سبز ", calaryG: 30, count: "100 گرم" },
    { id: 22, name: "موز ", calaryG: 70, count: "100 گرم" },
    { id: 23, name: "نارنگی", calaryG: 34, count: "100 گرم" },
    { id: 24, name: "هلوی تازه", calaryG: 45, count: "100 گرم" },
    { id: 25, name: "هلوی خشک", calaryG: 330, count: "100 گرم" },
    { id: 26, name: "هندوانه", calaryG: 23, count: "100 گرم" },
    { id: 27, name: "هویج", calaryG: 35, count: "100 گرم" },
    { id: 28, name: "آناناس	  ", calaryG: 45, count: "100 گرم" },
    { id: 29, name: "اسفناج خام ", calaryG: 25, count: "گرم 100 " },
    { id: 30, name: "بادمجان ", calaryG: 17, count: "100 گرم" },
    { id: 31, name: "پرتقال ", calaryG: 40, count: "100 گرم" },
    { id: 32, name: "توت فرنگی ", calaryG: 35, count: "100 گرم" },
    { id: 32, name: "چغندر آب پز", calaryG: 35, count: "100 گرم" },
  ],
  breads: [
    { id: 0, name: "آلبالو  ", calaryG: 60, count: "1 لیوان" },
    {
      id: 1,
      name: "نان سوخاری",
      calary: 35,
      count: "1 عدد ",
    },
    {
      id: 2,
      name: "نان (کف دست)",
      calary: 70,
      count: "1 عدد",
    },
    { id: 3, name: "نان خشک", calaryG: 360, count: "گرم 100 " },
    { id: 4, name: "نان جو", calaryG: 250, count: "گرم 100 " },
    { id: 5, name: "نان روغنی", calaryG: 450, count: "100 گرم" },
    { id: 6, name: "نان ساندویچی کامل ", calaryG: 70, count: "1 عدد" },
    { id: 7, name: "نان ساندویچی کوچک  ", calaryG: 70, count: "	نصف عدد" },
    { id: 8, name: "نان سیاه با سبوس  ", calaryG: 218, count: "100 گرم" },
    { id: 9, name: "نان گندم", calaryG: 250, count: "100 گرم" },
    { id: 10, name: "نان خامه ای متوسط", calaryG: 30, count: "1 عدد" },
  ],
  tanagholat: [
    { id: 0, name: "آجیل  ", calaryG: 750, count: "1 لیوان" },
    {
      id: 1,
      name: "آرد ذرت",
      calary: 370,
      count: "گرم 100 ",
    },
    {
      id: 2,
      name: "آرد گندم",
      calary: 360,
      count: "گرم 100 ",
    },
    { id: 3, name: "آجیل درهم", calaryG: 650, count: "گرم 100 " },
    { id: 4, name: "آدامس", calaryG: 2, count: "1 عدد" },
    { id: 5, name: "بادام زمینی بی پوست", calaryG: 560, count: "1 گرم" },
    { id: 6, name: "باقلا ", calaryG: 5, count: "1 عدد" },
    { id: 7, name: "پسته", calaryG: 8, count: "1 عدد" },
    { id: 8, name: "پفک", calaryG: 520, count: "100 گرم" },
    { id: 9, name: "پیاز", calaryG: 5, count: "1 عدد" },
    { id: 10, name: "تخم آفتابگردان", calaryG: 560, count: "100 گرم" },
    { id: 11, name: " تخم کدو", calaryG: 600, count: "100 گرم" },
    { id: 12, name: "تمبر هندی با دانه", calaryG: 115, count: "100 گرم" },
    { id: 13, name: "چای تلخ", calaryG: 0, count: "1 لیوان" },
    { id: 14, name: "چای شیرین  (۴حبه قند)", calaryG: 40, count: "1 لیوان" },
    { id: 15, name: "چیپس سیب زمینی", calaryG: 110, count: "10 عدد" },
    { id: 16, name: "خرما", calaryG: 20, count: "1 عدد" },
    { id: 17, name: "دسر ", calaryG: 180, count: "1 لیوان" },
  ],
};
